#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/git-config-resource-request.XXXXXX)

cat > $payload <&0

git_config_payload=$(jq -r '.source.git_config // []' < $payload)
configure_git_global "${git_config_payload}"

checksum=$(sha1sum < ~/.gitconfig | awk '{print $1}')

mkdir -p $destination

cp ~/.gitconfig $destination/.gitconfig
jq -n "{
  version: {checksum: $(echo $checksum | jq -R .)}
}" >&3
